### PR TITLE
switch to react-native-orientation fork

### PR DESCRIPTION
**Pull request by BrendanBerkley**

### CODE REVIEW

**Comment by BrendanBerkley** [comment]
https://github.com/lightbasenl/react-native-orientation/wiki/Migration-guide

This is what I followed. The fact that it exists makes me confident in this repo.

**Comment by BrendanBerkley** [comment]
I had Josh try to build this in iOS at the very end of the day and he got this error:

```
info ld: library not found for -lRCTOrientation

info clang: error

info : linker command failed with exit code 1 (use -v to see invocation)

info

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening EpubReader.xcodeproj

** BUILD FAILED **


The following commands produced analyzer issues:
    Analyze /Users/jmarantz/epubjs-rn/EpubReader/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp normal x86_64
    Analyze /Users/jmarantz/epubjs-rn/EpubReader/node_modules/react-native/React/Base/RCTModuleMethod.mm normal x86_64
(2 commands with analyzer issues)

The following build commands failed:
    Ld /Users/jmarantz/epubjs-rn/EpubReader/ios/build/EpubReader/Build/Products/Debug-iphonesimulator/EpubReader.app/EpubReader normal x86_64
(1 failure)
. Run CLI with --verbose flag for more details.
```

**Comment by fchasen** [comment]
Worked ok for me. That error above looks like the linking failed.

**Comment by fchasen** [comment]
Published as `epubjs-rn@0.1.3`

**Pull request merged**
